package staffmanagementsystem;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Lenovo
 */

public class StaffLeaveRequest extends javax.swing.JFrame {

    /**
     * Creates new form StaffLeaveRequest
     */
    public StaffLeaveRequest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        leaveRequestsTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        leaveRequestIDField = new javax.swing.JTextField();
        leaveStatusComboBox = new javax.swing.JComboBox<>();
        btnUpdateLeaveStatus = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Update Leave Request Status - Staff Management System");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        leaveRequestsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Leave Request ID ", "Staff Name", "Date Submitted", "Leave Start Date", "Leave End Date", "Leave Reason", "Leave Status"
            }
        ));
        leaveRequestsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                leaveRequestsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(leaveRequestsTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 92, 836, 350));

        jButton1.setBackground(new java.awt.Color(255, 102, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Show Table");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 52, 157, 34));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Leave Request ID:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Leave Status:");

        leaveStatusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Approved", "Rejected", " " }));

        btnUpdateLeaveStatus.setBackground(new java.awt.Color(0, 153, 0));
        btnUpdateLeaveStatus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUpdateLeaveStatus.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateLeaveStatus.setText("Update Leave Status");
        btnUpdateLeaveStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateLeaveStatusActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Update Leave Request Status");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(btnUpdateLeaveStatus)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(leaveStatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(leaveRequestIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(leaveRequestIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(leaveStatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(btnUpdateLeaveStatus)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 152, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 102, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("<- Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffmanagementsystem/88246.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 1270, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public class ShowTable{
        public void displayTable(){
            try {
            // Database connection
            String dbUrl = "jdbc:mysql://localhost/staffmanagementsystem";
            Connection connection = DriverManager.getConnection(dbUrl, "root", "Zxcv@7890");

            // SQL query
            String query = "SELECT " +
                    "l.leave_request_ID, " +
                    "CONCAT(s.first_name, ' ', s.last_name) AS staff_name, " +
                    "l.date_submitted, " +
                    "l.leave_start_date, " +
                    "l.leave_end_date, " +
                    "l.leave_reason, " +
                    "l.leave_status " +
                    "FROM LeaveRequests l " +
                    "JOIN staff s ON l.staff_ID = s.staff_id";

            // Execute the query
            PreparedStatement statement = connection.prepareStatement(query);
            ResultSet resultSet = statement.executeQuery();

            // Set up the table model
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Leave Request ID");
            model.addColumn("Staff Name");
            model.addColumn("Date Submitted");
            model.addColumn("Leave Start Date");
            model.addColumn("Leave End Date");
            model.addColumn("Leave Reason");
            model.addColumn("Leave Status");

            // Populate the table with data
            while (resultSet.next()) {
                String leaveRequestID = String.valueOf(resultSet.getInt("leave_request_ID"));
                String staffName = resultSet.getString("staff_name");
                String dateSubmitted = resultSet.getString("date_submitted");
                String leaveStartDate = resultSet.getString("leave_start_date");
                String leaveEndDate = resultSet.getString("leave_end_date");
                String leaveReason = resultSet.getString("leave_reason");
                String leaveStatus = resultSet.getString("leave_status");

                model.addRow(new Object[]{leaveRequestID, staffName, dateSubmitted, leaveStartDate, leaveEndDate, leaveReason, leaveStatus});
            }

            // Set the model to the table
            leaveRequestsTable.setModel(model);

            // Close connections
            resultSet.close();
            statement.close();
            connection.close();

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Database Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // Database connection
            String dbUrl = "jdbc:mysql://localhost/staffmanagementsystem";
            Connection connection = DriverManager.getConnection(dbUrl, "root", "Zxcv@7890");

            // SQL query
            String query = "SELECT " +
                    "l.leave_request_ID, " +
                    "CONCAT(s.first_name, ' ', s.last_name) AS staff_name, " +
                    "l.date_submitted, " +
                    "l.leave_start_date, " +
                    "l.leave_end_date, " +
                    "l.leave_reason, " +
                    "l.leave_status " +
                    "FROM LeaveRequests l " +
                    "JOIN staff s ON l.staff_ID = s.staff_id";

            // Execute the query
            PreparedStatement statement = connection.prepareStatement(query);
            ResultSet resultSet = statement.executeQuery();

            // Set up the table model
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Leave Request ID");
            model.addColumn("Staff Name");
            model.addColumn("Date Submitted");
            model.addColumn("Leave Start Date");
            model.addColumn("Leave End Date");
            model.addColumn("Leave Reason");
            model.addColumn("Leave Status");

            // Populate the table with data
            while (resultSet.next()) {
                String leaveRequestID = String.valueOf(resultSet.getInt("leave_request_ID"));
                String staffName = resultSet.getString("staff_name");
                String dateSubmitted = resultSet.getString("date_submitted");
                String leaveStartDate = resultSet.getString("leave_start_date");
                String leaveEndDate = resultSet.getString("leave_end_date");
                String leaveReason = resultSet.getString("leave_reason");
                String leaveStatus = resultSet.getString("leave_status");

                model.addRow(new Object[]{leaveRequestID, staffName, dateSubmitted, leaveStartDate, leaveEndDate, leaveReason, leaveStatus});
            }

            // Set the model to the table
            leaveRequestsTable.setModel(model);

            // Close connections
            resultSet.close();
            statement.close();
            connection.close();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Database Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void leaveRequestsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_leaveRequestsTableMouseClicked
        //Get the selected row index
        int selectedRow = leaveRequestsTable.getSelectedRow();

        if (selectedRow != -1) { // Check if a row is selected
            //Retrieve data from the selected row
            String leaveRequestId = leaveRequestsTable.getValueAt(selectedRow, 0).toString(); // Column 0: leave_request_ID
            String leaveStatus = leaveRequestsTable.getValueAt(selectedRow, 6).toString();    // Column 6: leave_status

            //Set the retrieved data into the text field and combo box
            leaveRequestIDField.setText(leaveRequestId);      
            leaveStatusComboBox.setSelectedItem(leaveStatus); 
        }
    }//GEN-LAST:event_leaveRequestsTableMouseClicked

    private void btnUpdateLeaveStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateLeaveStatusActionPerformed
        //Retrieve data from the text field and combo box
        String leaveRequestId = leaveRequestIDField.getText().trim();
        String leaveStatus = (String) leaveStatusComboBox.getSelectedItem();

        //Validate inputs
        if (leaveRequestId.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Leave Request ID is required!", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (leaveStatus == null || leaveStatus.equals("Select Status")) {
            JOptionPane.showMessageDialog(null, "Please select a valid Leave Status!", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            //Establish connection to the database
            String Path = "jdbc:mysql://localhost/staffmanagementsystem";
            Connection con = DriverManager.getConnection(Path, "root", "Zxcv@7890");

            //Prepare the SQL update query
            String updateQuery = "UPDATE LeaveRequests SET leave_status = ? WHERE leave_request_ID = ?";
            PreparedStatement pst = con.prepareStatement(updateQuery);

            //Set query parameters
            pst.setString(1, leaveStatus);        // Set the leave_status value
            pst.setInt(2, Integer.parseInt(leaveRequestId)); // Convert leaveRequestId to integer and set it

            //Execute the update query
            int rowsAffected = pst.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(null, "Leave Status updated successfully!", "Update Successful", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Leave Request ID not found. Update failed.", "Update Failed", JOptionPane.WARNING_MESSAGE);
            }

            //Refresh the table after update
            ShowTable st = new ShowTable();
            st.displayTable();

            // Close the database connection
            con.close();
        } catch (SQLException ex1) {
            JOptionPane.showMessageDialog(null, "Database Error: " + ex1.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (NumberFormatException ex2) {
            JOptionPane.showMessageDialog(null, "Invalid Leave Request ID format.", "Validation Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "An unexpected error occurred: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btnUpdateLeaveStatusActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        AdminDashboard ad = new AdminDashboard();
        ad.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffLeaveRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffLeaveRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffLeaveRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffLeaveRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffLeaveRequest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdateLeaveStatus;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField leaveRequestIDField;
    private javax.swing.JTable leaveRequestsTable;
    private javax.swing.JComboBox<String> leaveStatusComboBox;
    // End of variables declaration//GEN-END:variables
}
